name: TD Scheduled Query

# Controls when the workflow will run
on:
  pull_request:
    types: [open, reopened, closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    if: ${{ github.event.pull_request.merged == true }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true  # runs 'bundle install' and caches installed gems automatically

      - name: Install TD toolbelt
        env:
          TD_API_SERVER: https://api.treasure-data.com
          TD_API_KEY: ${{ secrets.TD_SECRET }}
          TD_EMAIL: ${{ secrets.TD_USER }}
        run:
          gem install td
          echo "[account]\n  user = $TD_EMAIL\n  apikey = $TD_API_KEY\n  endpoint = $TD_API_SERVER" > .td/td.conf

      - name: Start job
        # See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
        # also https://docs.github.com/en/rest/reference/pulls#check-if-a-pull-request-has-been-merged
        run: echo "Start update queries"

      - name: Update queries
        run: |
          diff=$(git show --name-only --oneline --pretty="format:" $GITHUB_REF | grep sql)
          for i in $diff; do n="$(basename $i .sql)"; td sched:update $n -q "$(cat $i)"; done

      - name: Finish job
        run: echo 'Finish the update!'
